version: '3.8'

services:
  backend:
    container_name: ecfr-analyzer-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ecfr-analyzer/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - backend-data:/data

  frontend:
    build:
      context: ./frontend
    container_name: ecfr-analyzer-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data: